---
- name: Restart Gitlab
  command: "docker restart {{ item }}"
  with_items:
    - "{{ gitlab_name }}"

- name: Remove Gitlab
  command: "docker stop {{ item }} && docker rm {{ item }}"
  register: results
  with_items:
    - "{{ gitlab_name }}"
  failed_when: >-
    results is failed and
    "No such container" not in results.stderr | default(false)
